services:
#  frontend:
#    build: 
#      context: ./frontend
#    container_name: transcendence_frontend
#    networks:
#      - external_network # rede externa para acesso público
#    environment:
#      - NODE_ENV=production
#    volumes:
#      - ./frontend:/app
#      - /app/node_modules
#
#  nginx:
#    build:
#      context: ./nginx
#      dockerfile: Dockerfile
#    container_name: transcendence_nginx
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./nginx/conf.d:/etc/nginx/conf.d
#      - ./frontend/dist:/usr/share/nginx/html:ro
#    networks:
#      - external_network # rede externa para acesso público
#    depends_on:
#      - frontend

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    environment:
      - PUBLIC_KEY_BASE64=${PUBLIC_KEY_BASE64}
    networks:
      - internal_network # rede interna para comunicação entre serviços
      - external_network # rede externa para acesso público
    ports:
      - "3000:3000"  # acessível publicamente com port 3000 exposta ao host/acesso publico
    depends_on:
      - auth-service
      - event-bus 
      # adicionar aqui todos os outros serviços internos que serão acessados/chamados pelo gateway
    volumes:
      - ./api-gateway:/app
      # - shared-keys:/app/keys

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    environment:
      - PRIVATE_KEY_BASE64=${PRIVATE_KEY_BASE64}
      - PUBLIC_KEY_BASE64=${PUBLIC_KEY_BASE64}
    networks:
      - internal_network # rede interna para comunicação entre serviços
    expose:
      - "4000"  # exposto apenas internamente para a network, não ao host
    volumes:
      - auth-data:/app/data # não precisa ser modificado, vamos usar VM
      - ./packages/event-bus:/app/packages/event-bus:ro # isso monta o diretório do event-bus no auth-service, permitindo que o auth-service acesse o event-bus
      # - shared-keys:/app/keys
    depends_on:
      - event-bus  

  event-bus:
    build:
      context: ./event-bus
    container_name: event-bus
    networks:
      - internal_network
    expose:
      - "6379"  # exposto apenas internamente para a network, não ao host

  user-mgmt:
    build:
      context: ./user-mgmt
    container_name: user-mgmt
    networks:
      - internal_network
    expose:
      - "5000"  # exposto apenas internamente para a network, não ao host
    volumes:
      - user-mgmt:/app/data # não precisa ser modificado, vamos usar VM
      - ./packages/event-bus:/app/packages/event-bus:ro # isso monta o diretório do event-bus no auth-service, permitindo que o auth-service acesse o event-bus


networks:
  internal_network:
    name: internal_network
    driver: bridge

  external_network:
    name: external_network
    driver: bridge

volumes:
  user-mgmt:
  auth-data:
  # shared-keys:

#volumes:
# auth-data: # isso aqui deve ser modificado para usar /goinfre no intra da 42
#    name: auth-data
