services:
  frontend-builder:
    build:
      context: ./Front
      dockerfile: Dockerfile
    volumes:
      - frontend-build:/app/dist
    profiles: ["builder"]

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    image: trans-api-gateway:1.0.1
    environment:
      - JWT_PUBLIC_KEY_BASE64=${JWT_PUBLIC_KEY_BASE64}
      - SSL_CERT_BASE64=${SSL_CERT_BASE64}
      - SSL_KEY_BASE64=${SSL_KEY_BASE64}
    networks:
      - internal_network
    ports:
      - "443:443"
    depends_on:
      - auth-service
      - event-bus
      - user-mgmt
    volumes:
      - avatars-data:/app/static/avatars # acesso a avatars do user-mgmt
      - frontend-build:/app/frontend
      - ./pckg/redis:/app/pckg/redis:ro # acesso ao redis e funções auxiliares


  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    image: auth-service:1.0.1
    environment:
      - JWT_PRIVATE_KEY_BASE64=${JWT_PRIVATE_KEY_BASE64}
      - JWT_PUBLIC_KEY_BASE64=${JWT_PUBLIC_KEY_BASE64}
    networks:
      - internal_network
    expose:
      - "4000"
    depends_on:
      - event-bus
    volumes:
      - auth-data:/app/data  # persistência de DB de autenticação
      - ./pckg/redis:/app/pckg/redis:ro # acesso ao redis e funções auxiliares

  event-bus:
    build:
      context: ./event-bus
    container_name: event-bus
    image: trans-event-bus:1.0.1
    networks:
      - internal_network
    expose:
      - "6379"
    volumes:
      - event-data:/data

  user-mgmt:
    build:
      context: ./user-mgmt
    container_name: user-mgmt
    image: trans-user-mgmt:1.0.1
    environment:
      - LOCAL_IP_BASE64=${LOCAL_IP_BASE64}
    networks:
      - internal_network
    expose:
      - "5000"
    volumes:
      - user-data:/app/data # persistência de DB e avatares de perfil de usuário
      - avatars-data:/app/avatars  # acesso a avatars do user-mgmt
      - ./pckg/redis:/app/pckg/redis:ro # acesso ao redis e funções auxiliares

  tournament-service:
    build:
      context: ./tournament-service
    container_name: tournament-service
    image: trans-tournament-service:1.0.1
    networks:
      - internal_network
    expose:
      - "8000"
    volumes:
      - ./pckg/redis:/app/pckg/redis:ro # acesso ao redis e funções auxiliares
      - tournament-data:/app/data
    depends_on:
      - event-bus

  game-server:
    build:
      context: ./game
      dockerfile: Dockerfile
    container_name: game-server
    image: trans-game-server:1.0.1
    environment:
      - JWT_PUBLIC_KEY_BASE64=${JWT_PUBLIC_KEY_BASE64}
      - SSL_CERT_BASE64=${SSL_CERT_BASE64}
      - SSL_KEY_BASE64=${SSL_KEY_BASE64}
    ports:
      - "3000:3000"
      - "3001:3001"
    expose:
      - "3000"
      - "3001"
    networks:
      - internal_network
    volumes:
      - ./pckg/redis:/app/pckg/redis:ro # acesso ao redis e funções auxiliares
    depends_on:
      - event-bus

networks:
  internal_network:
    name: internal_network
    driver: bridge

volumes:
  user-data:
    name: user-data
  auth-data:
    name: auth-data
  event-data:
    name: event-data
  tournament-data:
    name: tournament-data
  frontend-build:
    name: frontend-build
  avatars-data:
    name: avatars-data


