services:
  frontend-builder:
    build:
      context: ./Front
      dockerfile: Dockerfile
    environment:
      - PORT_HTTPS_GAME_SERVICE=${PORT_HTTPS_GAME_SERVICE}
      - PORT_WSS_GAME_SERVICE=${PORT_WSS_GAME_SERVICE}
    volumes:
      - frontend-build:/app/dist
    profiles: ["builder"]

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    image: trans-api-gateway:1.0.1
    environment:
      - PORT=${PORT_API_GATEWAY}
      - PORT_AUTH_SERVICE=${PORT_AUTH_SERVICE}
      - PORT_USER_MGMT=${PORT_USER_MGMT}
      - PORT_TOURNAMENT_SERVICE=${PORT_TOURNAMENT_SERVICE}
      - PORT_HTTPS_GAME_SERVICE=${PORT_HTTPS_GAME_SERVICE}
      - PORT_WSS_GAME_SERVICE=${PORT_WSS_GAME_SERVICE}
      - JWT_PUBLIC_KEY_BASE64=${JWT_PUBLIC_KEY_BASE64}
      - SSL_CERT_BASE64=${SSL_CERT_BASE64}
      - SSL_KEY_BASE64=${SSL_KEY_BASE64}
    networks:
      - internal_network
    ports:
      - "${PORT_API_GATEWAY}:${PORT_API_GATEWAY}"
    depends_on:
      - auth-service
      - event-bus
      - user-mgmt
    volumes:
      - avatars-data:/app/static/avatars # acesso a avatars do user-mgmt
      - frontend-build:/app/frontend
      - ./pckg:/app/pckg:ro # acesso ao pckges e funções auxiliares


  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    image: trans-auth-service:1.0.1
    environment:
      - PORT=${PORT_AUTH_SERVICE}
      - JWT_PRIVATE_KEY_BASE64=${JWT_PRIVATE_KEY_BASE64}
      - JWT_PUBLIC_KEY_BASE64=${JWT_PUBLIC_KEY_BASE64}
    networks:
      - internal_network
    expose:
      - "${PORT_AUTH_SERVICE}"
    depends_on:
      - event-bus
    volumes:
      - auth-data:/app/data  # persistência de DB de autenticação
      - ./pckg:/app/pckg:ro # acesso ao pckges e funções auxiliares

  event-bus:
    build:
      context: ./event-bus
    container_name: event-bus
    image: trans-event-bus:1.0.1
    networks:
      - internal_network
    expose:
      - "${PORT_EVENT_BUS}"
    volumes:
      - event-data:/data

  user-mgmt:
    build:
      context: ./user-mgmt
    container_name: user-mgmt
    image: trans-user-mgmt:1.0.1
    environment:
      - PORT=${PORT_USER_MGMT}
      - LOCAL_IP_BASE64=${LOCAL_IP_BASE64}
    networks:
      - internal_network
    expose:
      - "${PORT_USER_MGMT}"
    volumes:
      - user-data:/app/data # persistência de DB e avatares de perfil de usuário
      - avatars-data:/app/avatars  # acesso a avatars do user-mgmt
      - ./pckg:/app/pckg:ro # acesso ao pckges e funções auxiliares

  tournament-service:
    build:
      context: ./tournament-service
    container_name: tournament-service
    image: trans-tournament-service:1.0.1
    environment:
      - PORT=${PORT_TOURNAMENT_SERVICE}
    networks:
      - internal_network
    expose:
      - "${PORT_TOURNAMENT_SERVICE}"
    volumes:
      - ./pckg:/app/pckg:ro # acesso ao pckges e funções auxiliares
      - tournament-data:/app/data
    depends_on:
      - event-bus

  game-server:
    build:
      context: ./game
      dockerfile: Dockerfile
    container_name: game-server
    image: trans-game-server:1.0.1
    environment:
      - PORT_HTTPS=${PORT_HTTPS_GAME_SERVICE}
      - PORT_WSS=${PORT_WSS_GAME_SERVICE}
      - JWT_PUBLIC_KEY_BASE64=${JWT_PUBLIC_KEY_BASE64}
      - SSL_CERT_BASE64=${SSL_CERT_BASE64}
      - SSL_KEY_BASE64=${SSL_KEY_BASE64}
    ports:
      - "${PORT_HTTPS_GAME_SERVICE}:${PORT_HTTPS_GAME_SERVICE}"
      - "${PORT_WSS_GAME_SERVICE}:${PORT_WSS_GAME_SERVICE}"
    expose:
      - "${PORT_HTTPS_GAME_SERVICE}"
      - "${PORT_WSS_GAME_SERVICE}"
    networks:
      - internal_network
    volumes:
      - ./pckg:/app/pckg:ro # acesso ao pckges e funções auxiliares
    depends_on:
      - event-bus

networks:
  internal_network:
    name: internal_network
    driver: bridge

volumes:
  user-data:
    name: user-data
  auth-data:
    name: auth-data
  event-data:
    name: event-data
  tournament-data:
    name: tournament-data
  frontend-build:
    name: frontend-build
  avatars-data:
    name: avatars-data


